language: java
jdk: oraclejdk11

sudo: required


services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2

script :
  - docker build ./ -t springbootapp
  - docker-compose up --exit-code-from springbootapp


 
